import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Script from "next/script"; // ייבוא רכיב Script



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        
        <ToastContainer />
        {children}
        <Script
          src="https://cdn.enable.co.il/licenses/enable-L35097p7i1xdc4o3-1224-66728/init.js"
          strategy="afterInteractive" // הסקריפט ייטען לאחר טעינת הדף
        />
      </body>
    </html>
  );
}
